services:
  pg-db:
    image: postgres:14.3
    restart: always
    ports:
      - "5470:5432"
    environment:
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    container_name: teslodb
    volumes:
      - pg_teslo:/var/lib/postgresql/data
volumes:
  pg_teslo:
